package LoAServer.PublicEnums;

import LoAServer.LoAServer;

public enum GetAvailableRegionsReponses {
    NOT_CURRENT_TURN, DEDUCT_WILLPOWER, NOT_ENOUGH_WILLPOWER, CURRENT_HOUR_MAXED, CANNOT_MOVE_AFTER_FIGHT, CANNOT_MOVE_AFTER_MOVE_PRINCE, SUCCESS
}
