package LoAServer.PublicEnums;

public enum GetPrinceThoraldMovesResponses {
    PRINCE_DNE, NOT_CURRENT_TURN, DEDUCT_WILLPOWER, NOT_ENOUGH_WILLPOWER, CURRENT_HOUR_MAXED, CANNOT_MOVE_PRINCE_AFTER_FIGHT, CANNOT_MOVE_PRINCE_AFTER_MOVE, SUCCESS
}
